export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  
    USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  
    SESSION_REVOKED: 'SESSION_REVOKED',
    SESSION_EXPIRED: 'SESSION_EXPIRED'
  } as const
  
  export type ErrorCode =
    (typeof ERROR_CODES)[keyof typeof ERROR_CODES]