export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  
    SESSION_REVOKED: 'SESSION_REVOKED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',

    AREA_NAME_ALREADY_EXISTS: 'AREA_NAME_ALREADY_EXISTS',
    AREA_NOT_FOUND: 'AREA_NOT_FOUND',

    USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
    USER_INVALID_AREAS: 'USER_INVALID_AREAS',
    USER_PHONE_INCOMPLETE: 'USER_PHONE_INCOMPLETE',
    INVITATION_INVALID_TOKEN: 'INVITATION_INVALID_TOKEN',
    INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
    INVITATION_REVOKED: 'INVITATION_REVOKED',
    INVITATION_EXPIRED: 'INVITATION_EXPIRED',
    INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',

    PASSWORD_CONFIRMATION_MISMATCH:
      'PASSWORD_CONFIRMATION_MISMATCH',

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_ACTIVATED: 'USER_ALREADY_ACTIVATED',

    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_REFRESH_TOKEN_MISSING: 'AUTH_REFRESH_TOKEN_MISSING',
    AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
  } as const
  
  export type ErrorCode =
    (typeof ERROR_CODES)[keyof typeof ERROR_CODES]