export enum AuditAction {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    USER_RESTORED = 'USER_RESTORED',
    USER_ACTIVATED = 'USER_ACTIVATED',
    USER_DEACTIVATED = 'USER_DEACTIVATED',
  
    USER_INVITED = 'USER_INVITED',
    INVITATION_CREATED = 'INVITATION_CREATED',
    INVITATION_RESENT = 'INVITATION_RESENT',
    INVITATION_REVOKED = 'INVITATION_REVOKED',
    INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  
    ROLE_ASSIGNED = 'ROLE_ASSIGNED',
    ROLE_REMOVED = 'ROLE_REMOVED',
  
    PERMISSION_ASSIGNED = 'PERMISSION_ASSIGNED',
    PERMISSION_REMOVED = 'PERMISSION_REMOVED',
  
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
    PASSWORD_RESET = 'PASSWORD_RESET',
  
    SESSION_REVOKED = 'SESSION_REVOKED',
    SESSION_CREATED = 'SESSION_CREATED',
    SESSION_REFRESHED = 'SESSION_REFRESHED',

    AREA_CREATED = 'AREA_CREATED',
    AREA_UPDATED = 'AREA_UPDATED',
    AREA_ACTIVATED = 'AREA_ACTIVATED',
    AREA_DEACTIVATED = 'AREA_DEACTIVATED',
  }